on:
  workflow_dispatch:
  push:
    branches:
        - master
        - main
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
jobs:
  scan_job:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: BoostSecurity Scanner
        uses: peaudecastor/boost-security-scanner-github@v2
        with:
          action: scan
          additional_args: --partial
          api_token: ${{ secrets.BOOST_API_TOKEN }}
  java_job:
    name: Java Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
          cache: maven
      - name: Java Scanner
        uses: peaudecastor/boost-security-scanner-github@v2
        with:
          action: exec
          additional_args: --partial --require-full-repo
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          exec_command: "mvn clean compile com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dspotbugs.sarifOutput=true"
  complete_scan:
    name: Complete Scan
    needs: [scan_job, java_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Complete Scan
        uses: peaudecastor/boost-security-scanner-github@v2
        with:
          action: complete
          api_token: ${{ secrets.BOOST_API_TOKEN }}
